name: Fakelog Deployer
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'Error'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy using rsync
        run: rsync -avz ./ ubuntu@${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/Documents/test/fake-log
        # run: ssh ubuntu@${{ secrets.SSH_HOST }}
          
